### ISSUE TITLE
 9/10000 实时翻译 划译 May I ask what's going on with this.

### ISSUE THREAD

**Issue by qianse** [ntqbit/tdesktop-decrypter#4]
PS L:\SOFT\tdesktop-decrypter\tdesktop_decrypter>  python -m tdesktop_decrypter  tdata
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Lib\site-packages\tdesktop_decrypter\__main__.py", line 11, in <module>
    parsed_tdata = reader.read()
                   ^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\tdesktop_decrypter\decrypter.py", line 113, in read
    parsed_tdata.settings = self.read_settings()
                            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\tdesktop_decrypter\decrypter.py", line 137, in read_settings
    settings_tdf = read_tdf_file(self._path('settings'))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\tdesktop_decrypter\file_io.py", line 18, in read_tdf_file
    raise FileNotFoundError()
FileNotFoundError
PS L:\SOFT\tdesktop-decrypter\tdesktop_decrypter>

**Comment by ntqbit** [comment]
I haven't implemented a nice error display, for my purposes python's exception traceback was sufficient.

The error in your case indicates that there is no `settings` file in the specified tdata directory. The settings file is not strictly necessary for decryption of accounts and MTP keys, but for now the decrypter assumes that a valid telegram tdata directory always contains such a file; as far as I know, any tdata directory contains a `settings` (or `settingss`) file. Assuming that is the case, the error means that the specified tdata directory is not valid, it doesn't contain `setting` (or `settingss`) file, and `key_X` file, that contains encrypted accounts data.

Ensure the tdata path you specify is a correct path to a valid tdata directory.
